name: workflow overview
on:
  workflow_dispatch: 
  push:
    branches:
      - main
jobs:
  myselfhostedjob:
    name: myself
    runs-on: self-hosted 
    steps:
      - name: stepinselfhosted
        id: selfhostedid
        shell: cmd
        run: |
          echo this is multiline comment
          echo and this is job from self hosted
  testjob:
    name: newjob
    runs-on: ubuntu-latest
    steps:
      - name: step1
        id: stepId
        run: echo "Hello, to the first step"
      - name: step2
        id: shellStep
        shell: python
        run: print("Simran in Python")
